### ISSUE TITLE
Sparse matrix, SVD?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [akashgupta88/akashgupta#1]
Hey Akash,

I saw on Stack Overflow that you implemented sparse SVD in JS. Did you ever publish it online?

**Comment by akashgupta88** [comment]
Apologies for missing this! Never thought to have a comment on my personal website. The email notification must have gotten lost in the thread.

Yes, we implemented a sparse SVD in js, and I am looking for the code in my cloud storage if I ever backed it up, however we found it difficult to scale in terms of memory and efficiency, besides never knowing if it actually works. We ended up using a third party service like predicion.io (which has since been acquired by salesforce) which had just sprung up back in 2014-15.

**Comment by GeoffreyPlitt** [comment]
Gotcha, thanks!
